### ISSUE TITLE
Problems with parsing git messages.

### ISSUE THREAD

**Issue by afterdesign** [IonicaBizau/git-stats-importer#29] opened 2015-10-14 10:03 UTC
I tried to add stats for my [MacTerminal](https://github.com/afterdesign/MacTerminal) repo and I got this error. Tried a bit to debug and the problem is somewhere with ```gitlog-parser``` but it's a bunch of ifs and I can't understand what is going on there.

```javascript
→ ./node_modules/.bin/git-stats-importer -e rafal@malinowski.be
/Users/afterdesign/Library/Application Support/Sublime Text 3/Packages/MacTerminal/node_modules/gitlog-parser/index.js:37
      this._current.message += ('\n'+chunk);
                   ^

TypeError: Cannot read property 'message' of null
    at Gitlog._write (/Users/afterdesign/Library/Application Support/Sublime Text 3/Packages/MacTerminal/node_modules/gitlog-parser/index.js:37:20)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Gitlog.Writable.write (_stream_writable.js:207:11)
    at LineStream.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at LineStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at LineStream.Readable.push (_stream_readable.js:110:10)
    at LineStream.Transform.push (_stream_transform.js:128:32)
seq: needs negative decrement
```

**Comment by IonicaBizau** [comment] 2015-10-14 10:06
Thanks for the report, @afterdesign! :star2: 

@yorkie Can you please take a look here?

**Comment by yorkie** [comment] 2015-10-14 10:58
Ok, will have a take when I get home later

**Comment by yorkie** [comment] 2015-10-14 13:37
@afterdesign could you please show me how to reproduce this bug? Essentially the culprit is parser doesn't cover your special case of `git log`. So I need your `git log` result as well.

Thanks :-)

**Comment by afterdesign** [comment] 2015-10-14 13:44
And now I know where the problem is.
Set:
```
[color]
    ui = always
```

in ```~/.gitconfig```.
I switched to ```auto``` and now everything looks ok.

**Comment by IonicaBizau** [comment] 2015-10-14 13:45
@afterdesign Ah, maybe `git log` has an option to disable the colors. That should fix the thing.

**Comment by afterdesign** [comment] 2015-10-14 13:48
@IonicaBizau yeah, the ```auto``` flag fixed the problem. From git manual:
> The default setting is auto, which colors output when it’s going straight to a terminal, but omits the color-control codes when the output is redirected to a pipe or a file.

**Comment by IonicaBizau** [comment] 2015-10-14 15:49
No no no, I mean `git log` should have an option for that even you set in the `.gitconfig` file `ui = always`. This should be fixed in this tool. :smile:

**Comment by afterdesign** [comment] 2015-10-14 18:06
Oh, ok. Sorry for closing :)

**Comment by yorkie** [comment] 2015-10-15 02:44
So @IonicaBizau is this still a bug in gitlog-parser? Sorry, I maybe not have the time to read upstream your source code :-(

**Comment by IonicaBizau** [comment] 2015-10-15 05:32
@yorkie According to @afterdesign, no. It's just because of the coloring. We need to pass in the spawn call an option to disable the coloring. I will take care of that.

Thanks! :grin:

**Comment by afterdesign** [comment] 2015-10-15 06:44
Yeah I fixed that within my ```.gitconfig``` file.
To be sure that log is not using colors you can just go with ```git log --color=never```

**Comment by IonicaBizau** [comment] 2015-10-15 09:36
@afterdesign Thanks! Addressed in #30. :sparkles:

**Closed** 2015-10-15 09:36 UTC
Labels: bug

**Comment by IonicaBizau** [comment] 2015-10-15 09:38
:ship: **`2.2.0`** :tada:

**Comment by afterdesign** [comment] 2015-10-15 09:39
:trophy: :+1:

**Comment by IonicaBizau** [comment] 2015-10-15 09:39
:grin:
