### ISSUE TITLE
Ambigious argument '100'

### ISSUE THREAD

**Issue by matifol** [IonicaBizau/git-stats-importer#9] opened 2015-02-16 13:06 UTC
When I try to run the git-stats-importer in the root of my path, I get the following error:
```
error Error: Command failed: fatal: ambiguous argument '100': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by IonicaBizau** [comment] 2015-02-16 13:18
Hmm, looks like we should use `=` instead of space. I reproduced the issue when testing #8.

**Comment by IonicaBizau** [comment] 2015-02-16 13:43
We now can configure the separator in [`oargv@1.2.0`](https://github.com/IonicaBizau/node-oargv).

This should be fixed now:

```sh
$ npm update -g git-stats-importer@latest
```

**Comment by matifol** [comment] 2015-02-16 14:02
The importer seems to be working now. However, when I run `git-stats`, my calendar is empty. Am I missing something? Can this have something to do with the fact that we are running Assembla and not githib?

**Comment by IonicaBizau** [comment] 2015-02-16 14:07
When you imported the commits did you get an output below?

```sh
info  1 Imported commit: ...
info  2 Imported commit: ...
info  3 Imported commit: ...
```

This only imports your commits. Check if the email from your commits is the same with the one returned by `git config user.email` or `GIT_AUTHOR_EMAIL`.

**Comment by matifol** [comment] 2015-02-16 14:25
You got it. After I set `git config user.email` it's working perfectly :-)

Just to verify: here is my output

    info  1 Imported commit: ...
    info  Done.

![screen shot 2015-02-16 at 15 21 57](https://cloud.githubusercontent.com/assets/7047431/6213418/de8e3bb2-b5ef-11e4-8fa7-d3191f11acaf.png)

**Comment by IonicaBizau** [comment] 2015-02-16 14:29
Cool! :smile: So, can we close this issue?

**Comment by matifol** [comment] 2015-02-16 14:31
Yep! :)

**Closed** 2015-02-16 14:32 UTC
Labels: bug
